SUPPORTED_LANGUAGE={"EN":"English","FR":"Francais","ES":"Spanish","DE":"German"};

streettype=    {
        "FR": ["rue", "boulevard","bd",  "blvd", "avenue", "chemin", "rte", "route","impasse","pont","pt","parvis","passage", "place","plage","quai", "sentier", "voie", "cote"],
        "EN": ["allee", "alley", "anex", "arcade", "avenue", "bay", "bayou", "beach", "bend", "bluff", "bottom", "blvd", "boulevard", "branch", "bridge", "creek", "crossroad", "esplanade", "express", "expressway", "fort",  "garden", "gateway", "highway",  "hill", "hiway", "hollow", "inlet", "island", "isle",  "lake",  "lane", "light", "motorway", "mountain", "passage", "path", "place", "plain", "plaines", "plaza", "point", "port", , "quay", "road", "rue", "route", "square", "station", "street",  "tunnel",  "valley", "viaduct"] ,
	"ES":["transversal","rua","puerto","plaza","puente","glorieta","carrera","camino","passatge","autovia","autopista"],
        "DE":[],//no prefix for street in germany due to compound(always suffix?)
};
    

placetype={
"AdmBuilding":
        {
        "FR": ["bÃ¢timent administratif", "bÃ¢timent public"],
        "EN":["public building","administrative building"],
	"ES":["administartivo edificion"],
        "DE":[],
        },
"Airport":{"FR": ["aÃ©roport","aÃ©rodrome"],
        "EN":["airport"],
        "ES":["aeropuerto"],
        "DE":[],},
"Ambulance":{"FR": ["ambulance"],
        "EN":["ambulance"],
        "ES":["ambulancia"],
        "DE":[],},
"AmusePark":{"FR": ["parc d'attraction", "aire de jeux" ],
        "EN":["amuse park"],
        "ES":[],
        "DE":[],},
"Aqueduc":{"FR": ["aqueduc"],
        "EN":["aqueduc"],
        "ES":["Acueducto"],
        "DE":[],},
"ATM":{"FR": ["distributeur automatique de billets","DAB"],
        "EN":["ATM","automated teller machines"],
        "ES":["Cajero AutomÃ¡tico"],
        "DE":[],},
"Bank":{"FR": ["banque"],
        "EN":["bank"],
        "ES":["Banco"],
        "DE":[],},
"Bar":{"FR": ["bar","cafÃ©","bistro"],
        "EN":["bar","cafe","pub"],
        "ES":["Bar"],
        "DE":[],},
"Bay":{"FR": ["baie"],
        "EN":["bay"],
        "ES":["BahÃ­a"],
        "DE":[],},
"Beach":{"FR": ["plage"],
        "EN":["beach"],
        "ES":["Playa"],
        "DE":[],},
"Bridge":{"FR": ["pont"],
        "EN":["bridge"],
        "ES":["Puente"],
        "DE":[],},
"Building":{"FR": ["bÃ¢timent"],
        "EN":["building"],
        "ES":["Edificion"],
        "DE":[],},
"BusStation":{"FR": ["bus","arrÃªt de bus"],
        "EN":["bus","bus station"],
        "ES":["Parada de Bus"],
        "DE":[],},
"Camp":{"FR": ["camp"],
        "EN":["camp"],
        "ES":["Campamento"],
        "DE":[],},
"Camping":{"FR": ["camping"],
        "EN":["camping", "campsite", "campground"],
        "ES":["Camping"],
        "DE":[],},
"Canyon":{"FR": ["canyon"],
        "EN":["canyon"],
        "ES":["CaÃ±Ã³n"],
        "DE":[],},
"Casino":{"FR": ["casino"],
        "EN":["casino"],
        "ES":["Casino"],
        "DE":[],},
"Castle":{"FR": ["chÃ¢teau","manoir"],
        "EN":["castle","manor-house","manor"],
        "ES":["castillo"],
        "DE":[],},
"Cave":{"FR": ["cave"],
        "EN":["cave"],
        "ES":["cueva"],
        "DE":[],},
"Cemetery":{"FR": ["cimetiÃ¨re"],
        "EN":["Cemetery","graveyard"],
        "ES":["Cementerio"],
        "DE":[],},
"Cirque":{"FR": ["Cirque"],
        "EN":["cirque"],
        "ES":["Circo"],
        "DE":[],},
"CityHall":{"FR": ["mairie", "hÃ´tel de ville", "palais de la mairie"],
        "EN":["city Hall","town hall"],
        "ES":["Ayuntamiento"],
        "DE":[],},
"CitySubdivision":{"FR": ["arrondissement","quartier"],
        "EN":["city Subdivision", "quater","neighborhood"],
        "ES":["Municipios"],
        "DE":[],},
"Cliff":{"FR": ["falaise"],
        "EN":["cliff"],
        "ES":["Acantilado"],
        "DE":[],},
"Coast":{"FR": ["cote"],
        "EN":["coast"],
        "ES":["costa"],
        "DE":[],},
"CourtHouse":{"FR": ["palais de justice","tribunal"],
        "EN":["court House", "court"],
        "ES":["Cortes"],
        "DE":[],},
"Craft":{"FR": ["artisan"],
        "EN":["Craft","handworker"],
        "ES":["artesanÃ­Ã¡", "artesano"],
        "DE":[],},
"CustomsPost":{"FR": ["poste de douane","douane"],
        "EN":["Customs post"],
        "ES":["aduana"],
        "DE":[],},
"Dam":{"FR": ["barrage"],
        "EN":["dam"],
        "ES":["Presa"],
        "DE":[],},
"Desert":{"FR": ["desert"],
        "EN":["desert"],
        "ES":["desierto"],
        "DE":[],},
"Doctor":{"FR": ["docteur", "mÃ©decin","toubib"],
        "EN":["Doctor","physician"],
        "ES":["doctor"],
        "DE":[],},
"Factory":{"FR": ["usine"],
        "EN":["factory","industrial"],
        "ES":["FÃ¡brica"],
        "DE":[],},
"Falls":{"FR": ["chÃ»te d'eau","cascade"],
        "EN":["falls","waterfall"],
        "ES":["CatarÃ¡tas"],
        "DE":[],},
"Farm":{"FR": ["ferme","exploitation fermiÃ¨re","exploitation agricole"],
        "EN":["farm"],
        "ES":["Granja"],
        "DE":[],},
"Field":{"FR": ["domaine","terrain"],
        "EN":["field"],
        "ES":["Campo"],
        "DE":[],},
"FishingArea":{"FR": ["Ã©tang de pÃªche","lieu pour pÃªcher","pÃªche","zone de pÃªche"],
        "EN":["fishing area","fishing pond","fishing"],
        "ES":["area de pesca","Estanque de pesca"],
        "DE":[],},
"Fjord":{"FR": ["fjord"],
        "EN":["fjord"],
        "ES":["Fiordo"],
        "DE":[],},
"Forest":{"FR": ["forÃªt"],
        "EN":["forest"],
        "ES":["Bosque"],
        "DE":[],},
"Garden":{"FR": ["jardin","jardin public","jardins familiaux"],
        "EN":["public garden", "garden", "park"],
        "ES":["JardÃ­n pÃºblico", "JardÃ­n","Parque"],
        "DE":[],},
"Golf":{"FR": ["golf","terrain de golf"],
        "EN":["Golf"],
        "ES":["Golf"],
        "DE":[],},
"Gorge":{"FR": ["gorge"],
        "EN":["Gorge"],
        "ES":["Garganta"],
        "DE":[],},
"GrassLand":{"FR": ["prÃ©","prairie","pÃ¢ture"],
        "EN":["grassLand","meadow", "prairie", "grassland","pasture"],
        "ES":["Pradera","prado", "pradera", "praderas", "pastos"],
        "DE":[],},
"Gulf":{"FR": ["golfe"],
        "EN":["gulf"],
        "ES":["golfo"],
        "DE":[],},
"Hill":{"FR": ["colline"],
        "EN":["hill"],
        "ES":["Colina"],
        "DE":[],},
"Hospital":{"FR": ["hÃ´pital","clinique"],
        "EN":["hospital","infirmary","hospice","health_centre" ],
        "ES":["hospital", "hospicio"],
        "DE":[],},
"Hotel":{"FR": ["hÃ´tel","motel"],
        "EN":["hotel","motel","inn"],
        "ES":["hotel","motel"],
        "DE":[],},
"Island":{"FR": ["Ã®le"],
        "EN":["island"],
        "ES":["Isla"],
        "DE":[],},
"Lake":{"FR": ["lac"],
        "EN":["Lake","lough","lac"],
        "ES":["Lago"],
        "DE":[],},
"Library":{"FR": ["librairie"],
        "EN":["Library","bookcase"],
        "ES":["Biblioteca"],
        "DE":[],},
"LightHouse":{"FR": ["phare"],
        "EN":["light house"],
        "ES":["faro"],
        "DE":[],},
"Mall":{"FR": ["centre commercial","galerie marchande","rue piÃ¨tonne commerÃ§ante","zone commerciale"],
        "EN":["mall","shopping center", "shopping mall", "shops","retails"],
        "ES":["Centro Comercial", "Tiendas"],
        "DE":[],},
"Marsh":{"FR": ["marais","marÃ©cage"],
        "EN":["marsh"],
        "ES":["Pantano"],
        "DE":[],},
"MetroStation":{"FR": ["mÃ©tro","station de mÃ©tro"],
        "EN":["metro station","metro", "subway", "underground", "tube"],
        "ES":["EstaciÃ³n de metro","metro"],
        "DE":[],},
"Military":{"FR": ["caserne militaire","zone militaire"],
        "EN":["military"],
        "ES":["Militar"],
        "DE":[],},
"Mill":{"FR": ["moulin"],
        "EN":["mill","grinder"],
        "ES":["molino"],
        "DE":[],},
"Mine":{"FR": ["mine"],
        "EN":["mine"],
        "ES":["Mina"],
        "DE":[],},
"Mole":{"FR": ["digue"],
        "EN":["mole"],
        "ES":["Topo"],
        "DE":[],},
"Monument":{"FR": ["monument"],
        "EN":["monument"],
        "ES":["Monumento"],
        "DE":[],},
"Mound":{"FR": ["mont"],
        "EN":["mound"],
        "ES":["MontÃ­culo"],
        "DE":[],},
"Mountain":{"FR": ["montagne"],
        "EN":["mountain"],
        "ES":["MontaÃ±a"],
        "DE":[],},
"Museum":{"FR": ["musÃ©e"],
        "EN":["museum"],
        "ES":["Museo"],
        "DE":[],},
"NightClub":{"FR": ["night Club","club","discothÃ¨que","boite de nuit","club de nuit"],
        "EN":["night club", "night spot", "club"],
        "ES":["prostÃ­bulo", "club nocturno"],
        "DE":[],},
"Oasis":{"FR": ["oasis"],
        "EN":["oasis"],
        "ES":["oasis"],
        "DE":[],},
"ObservatoryPoint":{"FR": ["point d'observation"],
        "EN":["observatory point"],
        "ES":["observatorio"],
        "DE":[],},
"OperaHouse":{"FR": ["opÃ©ra"],
        "EN":["opera house","opera"],
        "ES":["teatro", "opera"],
        "DE":[],},
"Park":{"FR": ["parc"],
        "EN":["park", "garden", "kinder garten", "kinder garden" ],
        "ES":["Parque", "JardÃ­n"],
        "DE":[],},
"Parking":{"FR": ["parking","parking Ã  vÃ©los","place de parking"],
        "EN":["parking"],
        "ES":["Aparcamiento"],
        "DE":[],},
"Pharmacy":{"FR": ["pharmacie"],
        "EN":["pharmacy"],
        "ES":["farmacia"],
        "DE":[],},
"Picnic":{"FR": ["aire de pique-nique","pique nique"],
        "EN":["Picnic"],
        "ES":["Picnic","merienda"],
        "DE":[],},
"PolicePost":{"FR": ["police","gendarmerie","caserne de gendarmerie","poste de police"],
        "EN":["police station","police", "Police Post","constabulary"],
        "ES":["PolicÃ­a","PolicÃ­a Nacional"],
        "DE":[],},
"PoliticalEntity":{"FR": ["bÃ¢timent politique"],
        "EN":["political building", "political entity"],
        "ES":["centro PolÃ­tico"],
        "DE":[],},
"Pond":{"FR": ["Ã©tang"],
        "EN":["pond"],
        "ES":["estanque"],
        "DE":[],},
"Port":{"FR": ["port"],
        "EN":["port"],
        "ES":["puerto"],
        "DE":[],},
"PostOffice":{"FR": ["Poste","La poste","bureau de poste","boite aux lettres"],
        "EN":["post office","post","post box",],
        "ES":["oficina de Correos"],
        "DE":[],},
"Prison":{"FR": ["prison","maison d'arrÃªt"],
        "EN":["prison","jail"],
        "ES":["PrisiÃ³n", "carcel"],
        "DE":[],},
"Rail":{"FR": ["monorail","train-tram","voie ferrÃ©e","tramway","train"],
        "EN":["railway", "railroad", "rail"],
        "ES":["rail", "vÃ­as del Tren"],
        "DE":[],},
"RailRoadStation":{"FR": ["gare" ,"gare ferroviaire"],
        "EN":["station", "rail Road station", "rail station"],
        "ES":["estaciÃ³n de Tren"],
        "DE":[],},
"Ranch":{"FR": ["ranch"],
        "EN":["ranch"],
        "ES":["rancho"],
        "DE":[],},
"Religious":{"FR": ["lieu de priÃ¨re","lieu religieux","chapelle"],
        "EN":["place of worship","religious", "bethel", "place of preayer" , "place of prayer" ,"chapelle","church"],
        "ES":["iglesia", "catedral"],
        "DE":[],},
"Rental":{"FR": ["location"],
        "EN":["rental","location"],
        "ES":["alquiler"],
        "DE":[],},
"RestArea":{"FR": ["aire de repos" ,"aire de services"],
        "EN":["rest area"],
        "ES":["area de descanso"],
        "DE":[],},
"Restaurant":{"FR": ["restaurant"],
        "EN":["restaurant"],
        "ES":["Restaurante"],
        "DE":[],},
"School":{"FR": ["Ã©cole","lycÃ©e","collÃ¨ge","maternelle","facultÃ©","universitÃ©"],
        "EN":["school","college", "academy", "high school", "secondary school", "lyceum","preschool", "university"],
        "ES":["escuela","colegio", "academia", "universidad", "instituto de educaciÃ³n secundaria", "liceo"],
        "DE":[],},
"Shop":{"FR": ["magasin","commercant","boutique","supermarchÃ©","supÃ©rette","commerce","marchant","hypermarchÃ©"],
        "EN":["Shop,store", "boutique","market","market place", "supermarket"],
        "ES":["tienda", "boutique"],
        "DE":[],},
"Sport":{"FR": ["sport","lieu sportif","salle de sport","gymnase"],
        "EN":["sport","place to do sport","sports ground"],
        "ES":["sport","gimnasio"],
        "DE":[],},
"Stadium":{"FR": ["stade"],
        "EN":["stadium"],
        "ES":["estadio"],
        "DE":[],},
"SwimmingPool":{"FR": ["piscine","parc aquatique","lieu de baignade"],
        "EN":["swimming pool"],
        "ES":["piscina"],
        "DE":[],},
"Taxi":{"FR": ["taxi"],
        "EN":["taxi"],
        "ES":["taxi"],
        "DE":[],},
"Telephone":{"FR": ["tÃ©lÃ©phone"],
        "EN":["phone","telephone"],
        "ES":["telÃ©fono"],
        "DE":[],},
"Theater":{"FR": ["thÃ©Ã¢tre"],
        "EN":["theater"],
        "ES":["teatro"],
        "DE":[],},
"Toilet":{"FR": ["toilette"],
        "EN":["toilet"],
        "ES":["aseo", "baÃ±o"],
        "DE":[],},
"Tourism":{"FR": ["tourisme","lieu touristique"],
        "EN":["tourism"],
        "ES":["turismo"],
        "DE":[],},
"TourismInfo":{"FR": ["office de tourisme"],
        "EN":["tourism info"],
        "ES":["oficina de Turismo"],
        "DE":[],},
"Tower":{"FR": ["tour"],
        "EN":["tower"],
        "ES":["torre"],
        "DE":[],},
"Tunnel":{"FR": ["tunnel"],
        "EN":["tunnel"],
        "ES":["tunel"],
        "DE":[],},
"VendingMachine":{"FR": ["distributeur de boissons"],
        "EN":["vending machine"],
        "ES":["maquina de vending"],
        "DE":[],},
"Veterinary":{"FR": ["vÃ©terinaire","clinique vÃ©tÃ©rinaire"],
        "EN":["veterinary"],
        "ES":["veterinario"],
        "DE":[],},
"Vineyard":{"FR": ["vignoble"],
        "EN":["vineyard"],
        "ES":["viÃ±edo"],
        "DE":[],},
"Volcano":{"FR": ["volcan"],
        "EN":["volcano"],
        "ES":["volcÃ¡n"],
        "DE":[],},
"Zoo":{"FR": ["zoo","parc zoologique"],
        "EN":["zoo"],
        "ES":["zoo"],
        "DE":[],},
"Cinema":{"FR": ["cinema","film"],
        "EN":["cinema","film"],
        "ES":["cine", "pelÃ­cula", "teatro"],
        "DE":[],},
"Dentist":{"FR": ["dentiste","chirurgien dentiste"],
        "EN":["dentist"],
        "ES":["dentista"],
        "DE":[],},
"EmergencyPhone":{"FR": ["tÃ©lÃ©phone de secours","DAE","tÃ©lÃ©phone d'urgence","dÃ©fibrilateur","poste de secours"],
        "EN":["emergency phone"],
        "ES":["tÃ©lefono de emergencia"],
        "DE":[],},
"FerryTerminal":{"FR": ["terminal de ferry"],
        "EN":["ferry terminal"],
        "ES":["parada del ferry"],
        "DE":[],},
"FireStation":{"FR": ["pompier","caserne de pompiers"],
        "EN":["fire Station","fire hydrant"],
        "ES":["parque de bomberos"],
        "DE":[],},
"Fountain":{"FR": ["fontaine"],
        "EN":["fountain"],
        "ES":["Fuente"],
        "DE":[],},
"Fuel":{"FR": ["station essence","station service","essence"],
        "EN":["fuel","gas"],
        "ES":["estaciÃ³n de servicio", "gasolinera"],
        "DE":[],}
};

translation={
"near":{
"FR": "prÃ¨s de",
"EN": "near",
"ES": "cerca",
"DE": "nahe"
},
"choosepoitype":{
"FR": "Lieu ou addresse",
"EN": "Place or address",
"ES": "lugar o la direcciÃ³n",
"DE": "Ort oder adresse"
},
"placeholder":{
"FR": "Entrez un lieu, une addresse, ou une coordonÃ©e GPS / DMS",
"EN": "Enter an address, GPS or DMS coordinates",
"ES": "Introduzca una direcciÃ³n, GPS o DMS coordinan",
"DE": "Geben Sie eine Adresse, GPS-Koordinate oder DMS"
},
"nosuggestion":{
"FR": "Aucune suggestion, cliquer sur le bouton rechercher",
"EN": "no suggestions, please click the search button",
"ES": "ninguna sugerencia, por favor haga clic en el botÃ³n de bÃºsqueda",
"DE": "keine VorschlÃ¤ge, bitte klicken Sie auf die Suchtaste"
},
"searcharound":{
"FR": "chercher aux alentours",
"EN": "search around",
"ES": "buscar alrededor",
"DE": "herumsuchen"
},
"search":{
"FR": "chercher",
"EN": "find",
"ES": "encontrar",
"DE": "Suche"
},
"routeto":{
"FR": "ItinÃ©raire",
"EN": "Route",
"ES": "Ruta",
"DE": "Route"
}


}



charMap = {
'áºš':'a',
'Ã':'a',
'Ã¡':'a',
'Ã€':'a',
'Ã ':'a',
'Ä‚':'a',
'Äƒ':'a',
'áº®':'a',
'áº¯':'a',
'áº°':'a',
'áº±':'a',
'áº´':'a',
'áºµ':'a',
'áº²':'a',
'áº³':'a',
'Ã‚':'a',
'Ã¢':'a',
'áº¤':'a',
'áº¥':'a',
'áº¦':'a',
'áº§':'a',
'áºª':'a',
'áº«':'a',
'áº¨':'a',
'áº©':'a',
'Ç':'a',
'ÇŽ':'a',
'Ã…':'a',
'Ã¥':'a',
'Çº':'a',
'Ç»':'a',
'Ã„':'a',
'Ã¤':'a',
'Çž':'a',
'ÇŸ':'a',
'Ãƒ':'a',
'Ã£':'a',
'È¦':'a',
'È§':'a',
'Ç ':'a',
'Ç¡':'a',
'Ä„':'a',
'Ä…':'a',
'Ä€':'a',
'Ä':'a',
'áº¢':'a',
'áº£':'a',
'È€':'a',
'È':'a',
'È‚':'a',
'Èƒ':'a',
'áº ':'a',
'áº¡':'a',
'áº¶':'a',
'áº·':'a',
'áº¬':'a',
'áº­':'a',
'á¸€':'a',
'á¸':'a',
'Èº':'a',
'â±¥':'a',
'Ç¼':'a',
'Ç½':'a',
'Ç¢':'a',
'Ç£':'a',
'á¸‚':'b',
'á¸ƒ':'b',
'á¸„':'b',
'á¸…':'b',
'á¸†':'b',
'á¸‡':'b',
'Éƒ':'b',
'Æ€':'b',
'áµ¬':'b',
'Æ':'b',
'É“':'b',
'Æ‚':'b',
'Æƒ':'b',
'Ä†':'c',
'Ä‡':'c',
'Äˆ':'c',
'Ä‰':'c',
'ÄŒ':'c',
'Ä':'c',
'ÄŠ':'c',
'Ä‹':'c',
'Ã‡':'c',
'Ã§':'c',
'á¸ˆ':'c',
'á¸‰':'c',
'È»':'c',
'È¼':'c',
'Æ‡':'c',
'Æˆ':'c',
'É•':'c',
'ÄŽ':'d',
'Ä':'d',
'á¸Š':'d',
'á¸‹':'d',
'á¸':'d',
'á¸‘':'d',
'á¸Œ':'d',
'á¸':'d',
'á¸’':'d',
'á¸“':'d',
'á¸Ž':'d',
'á¸':'d',
'Ä':'d',
'Ä‘':'d',
'áµ­':'d',
'Æ‰':'d',
'É–':'d',
'ÆŠ':'d',
'É—':'d',
'Æ‹':'d',
'ÆŒ':'d',
'È¡':'d',
'Ã°':'d',
'Ã‰':'e',
'Æ':'e',
'ÆŽ':'e',
'Ç':'e',
'Ã©':'e',
'Ãˆ':'e',
'Ã¨':'e',
'Ä”':'e',
'Ä•':'e',
'ÃŠ':'e',
'Ãª':'e',
'áº¾':'e',
'áº¿':'e',
'á»€':'e',
'á»':'e',
'á»„':'e',
'á»…':'e',
'á»‚':'e',
'á»ƒ':'e',
'Äš':'e',
'Ä›':'e',
'Ã‹':'e',
'Ã«':'e',
'áº¼':'e',
'áº½':'e',
'Ä–':'e',
'Ä—':'e',
'È¨':'e',
'È©':'e',
'á¸œ':'e',
'á¸':'e',
'Ä˜':'e',
'Ä™':'e',
'Ä’':'e',
'Ä“':'e',
'á¸–':'e',
'á¸—':'e',
'á¸”':'e',
'á¸•':'e',
'áºº':'e',
'áº»':'e',
'È„':'e',
'È…':'e',
'È†':'e',
'È‡':'e',
'áº¸':'e',
'áº¹':'e',
'á»†':'e',
'á»‡':'e',
'á¸˜':'e',
'á¸™':'e',
'á¸š':'e',
'á¸›':'e',
'É†':'e',
'É‡':'e',
'Éš':'e',
'É':'e',
'á¸ž':'f',
'á¸Ÿ':'f',
'áµ®':'f',
'Æ‘':'f',
'Æ’':'f',
'Ç´':'g',
'Çµ':'g',
'Äž':'g',
'ÄŸ':'g',
'Äœ':'g',
'Ä':'g',
'Ç¦':'g',
'Ç§':'g',
'Ä ':'g',
'Ä¡':'g',
'Ä¢':'g',
'Ä£':'g',
'á¸ ':'g',
'á¸¡':'g',
'Ç¤':'g',
'Ç¥':'g',
'Æ“':'g',
'É ':'g',
'Ä¤':'h',
'Ä¥':'h',
'Èž':'h',
'ÈŸ':'h',
'á¸¦':'h',
'á¸§':'h',
'á¸¢':'h',
'á¸£':'h',
'á¸¨':'h',
'á¸©':'h',
'á¸¤':'h',
'á¸¥':'h',
'á¸ª':'h',
'á¸«':'h',
'H':'h',
'Ì±':'h',
'áº–':'h',
'Ä¦':'h',
'Ä§':'h',
'â±§':'h',
'â±¨':'h',
'Ã':'i',
'Ã­':'i',
'ÃŒ':'i',
'Ã¬':'i',
'Ä¬':'i',
'Ä­':'i',
'ÃŽ':'i',
'Ã®':'i',
'Ç':'i',
'Ç':'i',
'Ã':'i',
'Ã¯':'i',
'á¸®':'i',
'á¸¯':'i',
'Ä¨':'i',
'Ä©':'i',
'Ä°':'i',
'i':'i',
'Ä®':'i',
'Ä¯':'i',
'Äª':'i',
'Ä«':'i',
'á»ˆ':'i',
'á»‰':'i',
'Èˆ':'i',
'È‰':'i',
'ÈŠ':'i',
'È‹':'i',
'á»Š':'i',
'á»‹':'i',
'á¸¬':'i',
'á¸­':'i',
'I':'i',
'Ä±':'i',
'Æ—':'i',
'É¨':'i',
'Ä´':'j',
'Äµ':'j',
'J':'j',
'ÌŒ':'j',
'Ç°':'j',
'È·':'j',
'Éˆ':'j',
'É‰':'j',
'Ê':'j',
'ÉŸ':'j',
'Ê„':'j',
'á¸°':'k',
'á¸±':'k',
'Ç¨':'k',
'Ç©':'k',
'Ä¶':'k',
'Ä·':'k',
'á¸²':'k',
'á¸³':'k',
'á¸´':'k',
'á¸µ':'k',
'Æ˜':'k',
'Æ™':'k',
'â±©':'k',
'â±ª':'k',
'Ä¹':'a',
'Äº':'l',
'Ä½':'l',
'Ä¾':'l',
'Ä»':'l',
'Ä¼':'l',
'á¸¶':'l',
'á¸·':'l',
'á¸¸':'l',
'á¸¹':'l',
'á¸¼':'l',
'á¸½':'l',
'á¸º':'l',
'á¸»':'l',
'Å':'l',
'Å‚':'l',
'Å':'l',
'Ì£':'l',
'Å‚':'l',
'Ì£':'l',
'Ä¿':'l',
'Å€':'l',
'È½':'l',
'Æš':'l',
'â± ':'l',
'â±¡':'l',
'â±¢':'l',
'É«':'l',
'É¬':'l',
'É­':'l',
'È´':'l',
'á¸¾':'m',
'á¸¿':'m',
'á¹€':'m',
'á¹':'m',
'á¹‚':'m',
'á¹ƒ':'m',
'É±':'m',
'Åƒ':'n',
'Å„':'n',
'Ç¸':'n',
'Ç¹':'n',
'Å‡':'n',
'Åˆ':'n',
'Ã‘':'n',
'Ã±':'n',
'á¹„':'n',
'á¹…':'n',
'Å…':'n',
'Å†':'n',
'á¹†':'n',
'á¹‡':'n',
'á¹Š':'n',
'á¹‹':'n',
'á¹ˆ':'n',
'á¹‰':'n',
'Æ':'n',
'É²':'n',
'È ':'n',
'Æž':'n',
'É³':'n',
'Èµ':'n',
'N':'n',
'Ìˆ':'n',
'n':'n',
'Ìˆ':'n',
'Ã“':'o',
'Ã³':'o',
'Ã’':'o',
'Ã²':'o',
'ÅŽ':'o',
'Å':'o',
'Ã”':'o',
'Ã´':'o',
'á»':'o',
'á»‘':'o',
'á»’':'o',
'á»“':'o',
'á»–':'o',
'á»—':'o',
'á»”':'o',
'á»•':'o',
'Ç‘':'o',
'Ç’':'o',
'Ã–':'o',
'Ã¶':'o',
'Èª':'o',
'È«':'o',
'Å':'o',
'Å‘':'o',
'Ã•':'o',
'Ãµ':'o',
'á¹Œ':'o',
'á¹':'o',
'á¹Ž':'o',
'á¹':'o',
'È¬':'o',
'È­':'o',
'È®':'o',
'È¯':'o',
'È°':'o',
'È±':'o',
'Ã˜':'o',
'Ã¸':'o',
'Ç¾':'o',
'Ç¿':'o',
'Çª':'o',
'Ç«':'o',
'Ç¬':'o',
'Ç­':'o',
'ÅŒ':'o',
'Å':'o',
'á¹’':'o',
'á¹“':'o',
'á¹':'o',
'á¹‘':'o',
'á»Ž':'o',
'á»':'o',
'ÈŒ':'o',
'È':'o',
'ÈŽ':'o',
'È':'o',
'Æ ':'o',
'Æ¡':'o',
'á»š':'o',
'á»›':'o',
'á»œ':'o',
'á»':'o',
'á» ':'o',
'á»¡':'o',
'á»ž':'o',
'á»Ÿ':'o',
'á»¢':'o',
'á»£':'o',
'á»Œ':'o',
'á»':'o',
'á»˜':'o',
'á»™':'o',
'ÆŸ':'o',
'Éµ':'o',
'á¹”':'p',
'á¹•':'p',
'á¹–':'p',
'á¹—':'p',
'â±£':'p',
'Æ¤':'p',
'Æ¥':'p',
'P':'p',
'Ìƒ':'p',
'p':'p',
'Ìƒ':'p',
'Ê ':'q',
'ÉŠ':'q',
'É‹':'q',
'Å”':'r',
'Å•':'r',
'Å˜':'r',
'Å™':'r',
'á¹˜':'r',
'á¹™':'r',
'Å–':'r',
'Å—':'r',
'È':'r',
'È‘':'r',
'È’':'r',
'È“':'r',
'á¹š':'r',
'á¹›':'r',
'á¹œ':'r',
'á¹':'r',
'á¹ž':'r',
'á¹Ÿ':'r',
'ÉŒ':'r',
'É':'r',
'áµ²':'r',
'É¼':'r',
'â±¤':'r',
'É½':'r',
'É¾':'r',
'áµ³':'r',
'ÃŸ':'s',
'Åš':'s',
'Å›':'s',
'á¹¤':'s',
'á¹¥':'s',
'Åœ':'s',
'Å':'s',
'Å ':'s',
'Å¡':'s',
'á¹¦':'s',
'á¹§':'s',
'á¹ ':'s',
'á¹¡':'s',
'áº›':'s',
'Åž':'s',
'ÅŸ':'s',
'á¹¢':'s',
'á¹£':'s',
'á¹¨':'s',
'á¹©':'s',
'È˜':'s',
'È™':'s',
'Ê‚':'s',
'S':'s',
'Ì©':'s',
's':'s',
'Ì©':'s',
'Ãž':'t',
'Ã¾':'t',
'Å¤':'t',
'Å¥':'t',
'T':'t',
'Ìˆ':'t',
'áº—':'t',
'á¹ª':'t',
'á¹«':'t',
'Å¢':'t',
'Å£':'t',
'á¹¬':'t',
'á¹­':'t',
'Èš':'t',
'È›':'t',
'á¹°':'t',
'á¹±':'t',
'á¹®':'t',
'á¹¯':'t',
'Å¦':'t',
'Å§':'t',
'È¾':'t',
'â±¦':'t',
'áµµ':'t',
'Æ«':'t',
'Æ¬':'t',
'Æ­':'t',
'Æ®':'t',
'Êˆ':'t',
'È¶':'t',
'Ãš':'u',
'Ãº':'u',
'Ã™':'u',
'Ã¹':'u',
'Å¬':'u',
'Å­':'u',
'Ã›':'u',
'Ã»':'u',
'Ç“':'u',
'Ç”':'u',
'Å®':'u',
'Å¯':'u',
'Ãœ':'u',
'Ã¼':'u',
'Ç—':'u',
'Ç˜':'u',
'Ç›':'u',
'Çœ':'u',
'Ç™':'u',
'Çš':'u',
'Ç•':'u',
'Ç–':'u',
'Å°':'u',
'Å±':'u',
'Å¨':'u',
'Å©':'u',
'á¹¸':'u',
'á¹¹':'u',
'Å²':'u',
'Å³':'u',
'Åª':'u',
'Å«':'u',
'á¹º':'u',
'á¹»':'u',
'á»¦':'u',
'á»§':'u',
'È”':'u',
'È•':'u',
'È–':'u',
'È—':'u',
'Æ¯':'u',
'Æ°':'u',
'á»¨':'u',
'á»©':'u',
'á»ª':'u',
'á»«':'u',
'á»®':'u',
'á»¯':'u',
'á»¬':'u',
'á»­':'u',
'á»°':'u',
'á»±':'u',
'á»¤':'u',
'á»¥':'u',
'á¹²':'u',
'á¹³':'u',
'á¹¶':'u',
'á¹·':'u',
'á¹´':'u',
'á¹µ':'u',
'É„':'u',
'Ê‰':'u',
'á¹¼':'v',
'á¹½':'v',
'á¹¾':'v',
'á¹¿':'v',
'Æ²':'v',
'Ê‹':'v',
'áº‚':'w',
'áºƒ':'w',
'áº€':'w',
'áº':'w',
'Å´':'w',
'Åµ':'w',
'W':'w',
'ÌŠ':'w',
'áº˜':'w',
'áº„':'w',
'áº…':'w',
'áº†':'w',
'áº‡':'w',
'áºˆ':'w',
'áº‰':'w',
'áºŒ':'x',
'áº':'x',
'áºŠ':'x',
'áº‹':'x',
'Ã':'y',
'Ã½':'y',
'á»²':'y',
'á»³':'y',
'Å¶':'y',
'Å·':'y',
'Y':'y',
'ÌŠ':'y',
'áº™':'y',
'Å¸':'y',
'Ã¿':'y',
'á»¸':'y',
'á»¹':'y',
'áºŽ':'y',
'áº':'y',
'È²':'y',
'È³':'y',
'á»¶':'y',
'á»·':'y',
'á»´':'y',
'á»µ':'y',
'Ê':'y',
'ÉŽ':'y',
'É':'y',
'Æ³':'y',
'Æ´':'y',
'Å¹':'z',
'Åº':'z',
'áº':'z',
'áº‘':'z',
'Å½':'z',
'Å¾':'z',
'Å»':'z',
'Å¼':'z',
'áº’':'z',
'áº“':'z',
'áº”':'z',
'áº•':'z',
'Æµ':'z',
'Æ¶':'z',
'È¤':'z',
'È¥':'z',
'Ê':'z',
'Ê‘':'z',
'â±«':'z',
'â±¬':'z',
'Ç®':'z',
'Ç¯':'z',
'Æº':'z',

// Roman fullwidth ascii equivalents: 0xff00 to 0xff5e
'ï¼’':'2',
'ï¼–':'6',
'ï¼¢':'B',
'ï¼¦':'F',
'ï¼ª':'J',
'ï¼®':'N',
'ï¼²':'R',
'ï¼¶':'V',
'ï¼º':'Z',
'ï½‚':'b',
'ï½†':'f',
'ï½Š':'j',
'ï½Ž':'n',
'ï½’':'r',
'ï½–':'v',
'ï½š':'z',
'ï¼‘':'1',
'ï¼•':'5',
'ï¼™':'9',
'ï¼¡':'A',
'ï¼¥':'E',
'ï¼©':'I',
'ï¼­':'M',
'ï¼±':'Q',
'ï¼µ':'U',
'ï¼¹':'Y',
'ï½':'a',
'ï½…':'e',
'ï½‰':'i',
'ï½':'m',
'ï½‘':'q',
'ï½•':'u',
'ï½™':'y',
'ï¼':'0',
'ï¼”':'4',
'ï¼˜':'8',
'ï¼¤':'D',
'ï¼¨':'H',
'ï¼¬':'L',
'ï¼°':'P',
'ï¼´':'T',
'ï¼¸':'X',
'ï½„':'d',
'ï½ˆ':'h',
'ï½Œ':'l',
'ï½':'p',
'ï½”':'t',
'ï½˜':'x',
'ï¼“':'3',
'ï¼—':'7',
'ï¼£':'C',
'ï¼§':'G',
'ï¼«':'K',
'ï¼¯':'O',
'ï¼³':'S',
'ï¼·':'W',
'ï½ƒ':'c',
'ï½‡':'g',
'ï½‹':'k',
'ï½':'o',
'ï½“':'s',
'ï½—':'w'};